// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function HandleFileDrop(arg1) {
  return window['go']['main']['App']['HandleFileDrop'](arg1);
}

export function ProcessFolder(arg1, arg2) {
  return window['go']['main']['App']['ProcessFolder'](arg1, arg2);
}

export function ReadFileContent(arg1) {
  return window['go']['main']['App']['ReadFileContent'](arg1);
}

export function ReadSettingsFile() {
  return window['go']['main']['App']['ReadSettingsFile']();
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function SelectFile() {
  return window['go']['main']['App']['SelectFile']();
}

export function WriteSettingsFile(arg1) {
  return window['go']['main']['App']['WriteSettingsFile'](arg1);
}
